export const IMAGES = {
    wall: 'assets/brick_wall.png',
    grass: 'assets/grass.jpg',
    duck: 'assets/duck/walk/front/1.png',
    duck2: 'assets/duck/walk/front/2.png',
    duck3: 'assets/duck/walk/front/3.png',
    duck4: 'assets/duck/walk/front/4.png',
    duckBack: 'assets/duck/walk/back/1.png',
    duckBack2: 'assets/duck/walk/back/2.png',
    duckBack3: 'assets/duck/walk/back/3.png',
    duckBack4: 'assets/duck/walk/back/4.png',
    barrell:'assets/barrell.png',
    hillside: 'assets/hillside.png',
    sky1: 'assets/sky1.png',
} as const;
